language: node_js
node_js:
  - "node"
script:
  - npm run lint
  - npm run test

sudo: required

addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
     - fluxbox
     - python-pygments

before_install:
  - sudo apt install snapd
  - sudo snap install hugo
  - PATH=$PATH:/snap/bin

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
