languageCode = "en"
title = "Markus Oberlehner"
baseURL = "https://markus.oberlehner.net/"
enableRobotsTXT = true
SectionPagesMenu = "main"
disableHugoGeneratorInject = true
PygmentsCodeFences = true
PygmentsUseClasses = true
theme = "mao"

[params]
  description = "Markus Oberlehner writes articles about Vue.js, JavaScript, CSS, Test Driven Development and Front-End Architecture in general."
  author = "Markus Oberlehner"
  images = ["https://markus.oberlehner.net/images/f_auto,q_auto/v1532158513/blog/assets/markus-oberlehner-meta-2017-06"]

[[menu.main]]
  name = "Home"
  weight = -100
  identifier = "home"
  url = "/"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  lego = "lego"
